// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ioroojajrlajsxsdjrkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlvcm9vamFqcmxhanN4c2RqcmtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NzgxMDUsImV4cCI6MjA3NDM1NDEwNX0.xvBjvVmt-AwR347_RFUi1UqaW_XbjLEEZ6S4f1GGVio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});