// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ioszhuazyewkesfbdmxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlvc3podWF6eWV3a2VzZmJkbXhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMDQyNzMsImV4cCI6MjA3NDU4MDI3M30.3qfn4oq1km2HHA5lwFMopahGWAXNNGKJaZoln4ZClU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});